# Generated by Django 5.2 on 2025-05-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(help_text='Используйте HTML-теги для форматирования', verbose_name='Содержание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('category', models.CharField(choices=[('news', 'О компании'), ('article', 'Оплата'), ('promo', 'Доставка')], max_length=50, verbose_name='Категория')),
            ],
        ),
    ]
