# Generated by Django 5.2 on 2025-05-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('Одиночные цветы', 'Одиночные цветы'), ('Букеты', 'Букеты')], default='Одиночные цветы', max_length=100, verbose_name='Группа')),
                ('subgroup', models.CharField(choices=[('Розы', 'Розы'), ('Хризантемы', 'Хризантемы')], default='Розы', max_length=100, verbose_name='Подгруппа')),
                ('flower_type', models.CharField(choices=[('Красные розы', 'Красные розы'), ('Белые розы', 'Белые розы'), ('Простые хризантемы', 'Простые хризантемы'), ('Декоративные хризантемы', 'Декоративные хризантемы'),], default='Красные розы', max_length=100, verbose_name='Тип цветка')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Изображение')),
                ('is_new', models.BooleanField(default=False, verbose_name='Новинка')),
                ('is_bestseller', models.BooleanField(default=False, verbose_name='Хит продаж')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество на складе')),
            ],
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Цвет')),
                ('css_name', models.CharField(blank=True, max_length=50, verbose_name='CSS-класс')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвета',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Оценка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
    ]
